set -g mode-keys vi
set -g display-panes-time 5000

# bindings
bind-key x kill-pane
bind-key e run-shell 'f=$(mktemp); tmux capture-pane -pS - > "$f"; tmux display-popup -E "${EDITOR:-vim} \"$f\"; rm \"$f\""'

bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

bind-key -r C-h select-pane -L \; swap-pane -s !
bind-key -r C-j select-pane -D \; swap-pane -s !
bind-key -r C-k select-pane -U \; swap-pane -s !
bind-key -r C-l select-pane -R \; swap-pane -s !

# styling
set -g @ctp_bg "#24273a"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_yellow "#eed49f"
set -g @ctp_teal "#8bd5ca"
set -g @ctp_lavender "#b7bdf8"
set -g @ctp_overlay_2 "#939ab7"
set -g @ctp_overlay_0 "#6e738d"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_surface_0 "#363a4f"
set -g @ctp_mantle "#1e2030"
set -g @ctp_crust "#181926"

set -gF status-style "bg=#{@ctp_mantle},fg=#{@ctp_fg}"
set -gF message-style "fg=#{@ctp_teal},bg=#{@ctp_overlay_0},fill=#{@ctp_overlay_0}"
set -gF message-command-style "fg=#{@ctp_teal},bg=#{@ctp_overlay_0},fill=#{@ctp_overlay_0}"
set -gF menu-selected-style "fg=#{@ctp_fg},bold,bg=#{@ctp_overlay_0}"
set -gF pane-active-border-style "##{?pane_in_mode,fg=#{@ctp_lavender},##{?pane_synchronized,fg=#{@ctp_mauve},fg=#{@ctp_lavender}}}"
set -gF pane-border-style "fg=#{@ctp_overlay_0}"
set -gF popup-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"
set -gF popup-border-style "fg=#{@ctp_surface_0}"
set -gF window-status-activity-style "bg=#{@ctp_lavender},fg=#{@ctp_crust}"
set -gF window-status-bell-style "bg=#{@ctp_yellow},fg=#{@ctp_crust}"
set -gF mode-style "bg=#{@ctp_surface_0},bold"

set -g status-right ""
set -g status-left "#[bold] #{session_name} | "
set -gF window-status-format "#[fg=#{@ctp_crust},bg=#{@ctp_overlay_2}] ##I #[fg=#{@ctp_fg},bg=#{@ctp_surface_0}] ##T "
set -gF window-status-current-format "#[fg=#{@ctp_crust},bg=#{@ctp_mauve}] ##I #[fg=#{@ctp_fg},bg=#{@ctp_surface_1}] ##T "
